spring:
    application:
        name: player-service

    datasource:
        url: ${DB_URL:jdbc:postgresql://tournament-bd.postgres.database.azure.com:5432/playerdb?sslmode=require}
        username: ${DB_USER:Suzukie}
        password: ${DB_PASS:1340431NNNn}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    sql:
        init:
            mode: always

server:
    port: ${PORT:8080}

logging:
    level:
        root: INFO
        org.springframework: INFO
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE
        org.hibernate.orm.jdbc.bind: TRACE

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        prometheus:
            enabled: true
    metrics:
        export:
            prometheus:
                enabled: true

graphql:
    servlet:
        mapping: /graphql
        enabled: true
    tools:
        schema-location-pattern: graphql/*.graphqls

encryption:
    secret: ${ENCRYPTION_SECRET:1234567890123456}



spring:
    profiles:
        active: ${SPRING_PROFILES_ACTIVE:default}
